### ISSUE TITLE
Error with menu in doctor test browseSelectedResult

### ISSUE THREAD

**Issue by akevalion** [juliendelplanque/DrTests#100]
Pharo 8x64 mac

1. Open dr tests and run tests
2. You should have one error in your tests like this screenshot
![image](https://user-images.githubusercontent.com/10532890/70003325-8fedb800-1541-11ea-9217-c1f8cb8a1ea1.png)
3. Rightclick in Results: Errors->RSExamplesTests.
4. Select the menu item browse.

Current result, you have an error when you try to browse a class
![image](https://user-images.githubusercontent.com/10532890/70003427-d93e0780-1541-11ea-8176-028d1ee24ad2.png)

Expected result, the browse menu should allow to browse classes like methods

**Comment by juliendelplanque** [comment]
Hello,
Thanks for reporting.
I created a PR on Pharo main repository to fix this issue.
See Pharo issue https://github.com/pharo-project/pharo/issues/5312
See PR https://github.com/pharo-project/pharo/pull/5313
I close this issue.
