### ISSUE TITLE
Package search field as in Calypso would be convenient

### ISSUE THREAD

**Issue by cdlm** [juliendelplanque/DrTests#57]
…but then I'm thinking that should probably be a feature provided by the list view itself 🤔

**Comment by GDayne** [comment]
@cdlm we are waiting to https://github.com/pharo-spec/Spec/issues/538 be solved in spec

**Comment by cdlm** [comment]
okay, good to know :-)

**Comment by juliendelplanque** [comment]
In the end, we implemented a custom list widget providing list search waiting for Spec2 to provide this feature.

Closing the issue, we might or not replace our widget by the one built-in Spec.
