### ISSUE TITLE
Cannot browse test class

### ISSUE THREAD

**Issue by guillep** [juliendelplanque/DrTests#89]
Pharo-8.0.0+build.775.sha.979c57995a24ca1a45c890deafc70b209fc8193e (64 Bit)

1) I open dr test
2) select a package => a  list of classes appear
3) right click on a class => nothing happens

I'd like to be able to browse the class

**Comment by juliendelplanque** [comment]
Good idea

**Comment by juliendelplanque** [comment]
I proposed a fix for this issue on Pharo repository.
Related issue: https://github.com/pharo-project/pharo/issues/5315
Related PR: https://github.com/pharo-project/pharo/pull/5317

So, I close this issue, we can continue there.
